# Generated by Django 2.0.3 on 2018-12-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='there_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_answer', to='questions.Answer'),
        ),
    ]
