# Generated by Django 2.0.3 on 2018-12-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181225_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='input_point',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='there_input_field',
            field=models.IntegerField(default=-1),
        ),
    ]
