# Generated by Django 2.0.3 on 2018-12-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20181225_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='there_input_field',
            new_name='there_input_point',
        ),
    ]
