# Generated by Django 2.0.3 on 2018-12-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_percent',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
    ]
