# Generated by Django 2.0.3 on 2018-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_employermatch_locationmatch_positionmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmatch',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
